camunda.bpm:
  admin-user:
    id: admin
    password: admin
    firstName: Chuck
    lastName: Norris
  filter:
    create: All tasks

spring:
  config:
    import:
      - optional:classpath:cibseven-webclient.properties

  # H2 Database Configuration (File-based)
  datasource:
    url: jdbc:h2:file:./data/underwaise-db;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE
    driverClassName: org.h2.Driver
    username: sa
    password: password #  Very safe btw

  # JPA Configuration
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: validate

  # H2 Console (for development)
  h2:
    console:
      enabled: true
      path: /h2-console

  # Liquibase Configuration
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml

underwaise:
  aiServiceUrl: http://localhost:8000
  mailgun-domain: mg.underwaise.ch
  mailgun-api-key: 123

cibseven:
  webclient:
    services:
      basePath: services/v1
    # Engine rest
    engineRest:
      url: http://localhost:8080
    # BPM provider for Enterprise Edition
    # bpm:
    #   provider: org.cibseven.webapp.providers.SevenProviderEE

---
# Profile for MS SQL Server
spring:
  config:
    activate:
      on-profile: mssql
  jpa:
    properties:
      hibernate:
        type:
          preferred_uuid_jdbc_type: CHAR
